import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Authorize from "@/Components/Authorize";
import { connectDB } from "@/helper/db";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
connectDB()
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen">
          <Navbar />
          <Authorize>{children}</Authorize>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
